{{- if .Values.shareConfig.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "quark.serviceAccountName" . }}
  labels:
    {{- include "quark.labels" . | nindent 4 }}
  {{- with .Values.shareConfig.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
